name: CI

# Controls when the action will run. 
on:
  push:
    tags:
      - v* # Push events to v1 tag
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    if: ${{ !(github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest,windows-latest]
        python-version: [3.7]
    env:
      image_name: "start images"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # 您可以打印当前 Python 版本以测试矩阵
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Start build
        run: |
          pyinstaller --onefile Main.py
      - name: Create windows_archive
        if: ${{ startsWith(matrix.os, 'windows') }}
        env:
          image_name: ${{ matrix.os }}_Main.exe
        run: |
          cd dist
          ren Main.exe ${{ env.image_name }}
      - name: Create ubuntu_archive
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        env:
          image_name: ${{ matrix.os }}_Main
        run: |
          cd dist
          mv Main ${{ env.image_name }}
      - name: Create macos_archive
        if: ${{ startsWith(matrix.os, 'macos') }}
        env:
          image_name: ${{ matrix.os }}_Main
        run: |
          cd dist
          mv Main ${{ env.image_name }}
      - name: Upload images to Artifact
        if: ${{ github.event_name != 'release' && success() }}
        uses: actions/upload-artifact@v2.2.1
        with:
          name: ${{ matrix.os }}
          path: dist/*
      - name: Upload images to Releases
        if: ${{ github.event_name == 'release' && success() }}
        uses: svenstaro/upload-release-action@2.2.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
